function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 16-Dec-2020 11:55:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','hpr1','Color',[0 0 1]);
set(plot1(2),'DisplayName','mre11','Color',[1 0 0]);
set(plot1(3),'DisplayName','WT','Color',[0 1 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1(2),12,0.0208142875);
% Create datatip
datatip(plot1(2),'DataIndex',12);

% Create ylabel
ylabel({'MSD (\mu^2)'});

% Create xlabel
xlabel({'\tau ( ~37 sec)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.0345622119815675 15.0345622119816]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.12]);
box(axes1,'on');
hold(axes1,'off');
